### PR TITLE
Kazybek changes

### PR DESCRIPTION
**Pull request by Spatayev**

### CODE REVIEW

**Review by talgat-ruby — COMMENTED** [review]
I will approve. But forget about reset or normalize css

**Review by talgat-ruby — APPROVED** [review]

**Comment by talgat-ruby** [comment]
@bensteri @Gulfiya-01 please review

**Comment by Spatayev** [comment]
> I will approve. But forget about reset or normalize css

I setup them but didn't use it

**Review by bensteri — APPROVED** [review]

**Review by Gulfiya-01 — COMMENTED** [review]
Good!

**Pull request merged**
